### ISSUE TITLE
comments take up way too much space

### ISSUE THREAD

**Issue by Almenon** [TheTRUEHoohah/u-thehelperDroid#1]
https://www.reddit.com/r/botwatch/comments/7pia9o/is_there_any_way_to_contact_the_author_of_the/

**Comment by theREALaltoid** [comment]
Fixed! Thanks for the feedback. :)

**Comment by dashlink18** [comment]
The bot triggered on a comment that was a joke, it was a Vsauce meme on a post about Zelda. Is there a way the bot can detect if something is a meme or not? I’m not actually suicidal. Good job on the saving lives part though.
